### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by carodelafuente** [johnyboy21/colmaracademy#4]
Grade: Meets expectations.

You did a great job at matching the spec! Everything looks great and your code is very neat and easy to read-- keep it up! I would just say look over the comments I left you and familiarize yourself with more semantic tags and don't forget your semicolons on your symbols code :)

Moving forward, I would say use this site as a reference for future css needs: https://css-tricks.com/ it's a great resource with a tons of tutorials and will help you master css. You already did a great job using flexbox and responsive styling so you're on the right track!

Happy coding! 👾

**Comment by johnyboy21** [comment]
Thanks for the review!

It seems like I had a lot of "ah ha!" moments after the fact.  It's still a great feeling to be able to go from zero to website in just a few weeks.  I still have much to learn and am excited to continue learning from my many mistakes.  

Thanks again!

John
